### ISSUE TITLE
Good job done ! But I still don't know how to use it 

### ISSUE THREAD

**Issue by heyanyidui** [Michedev/VAE_anomaly_detection#2]
First of all, thanks for your code !

I don't know how to run your codes , and I hope you could update your README more detailly.

Maybe one more demo needs here, including how to deal with some dataset such as MNIST.

Thank you very  much ! I'm looking forward to your reply !

**Comment by Michedev** [comment]
Hey heyanyidui, thank you fthe feedback! Since my implementation uses dense layer in both encoder and decoder it cannot support MNIST dataset in this form, you have to reimplement encoder/decoder with convolutional layers or flatten mnist in order to feed into the model like _X_train_ in my code

**Comment by heyanyidui** [comment]
Thanks !
