### ISSUE TITLE
Likelihood assumption is not compatible with the output

### ISSUE THREAD

**Issue by scigeek72** [Michedev/VAE_anomaly_detection#4]
Hi,
I was looking for a similar implementation where I could output `mu` and `sigma` so that I can calculate the probability of the reconstructed output instead of just the reconstruction. Mathematically that means, the assumption of p(x|z) ~ N(mu, sigma**2*I) instead of just N(mu, I). This assumption modifies the loss function by introducing additional terms. For the output that you are implementing, I think you need to modify the `elbo` function where you are still using just the mse(true, pred).  Is there something I am missing? Thanks.

**Comment by Michedev** [comment]
I'm not sure to understand your question, but this implementation works in the way you have described; it outputs the distribution parameters of the reconstructed image (mu and sigma) then optimize the log-likelihood the input given the distribution parameters of the reconstructed image
